### ISSUE TITLE
Broken on node v0.6.14

### ISSUE THREAD

**Issue by teddyknox** [bdotdub/nodejs-chat#1]
teddyknox:server teddyknox$ node startServer.js 
The "sys" module is now called "util". It should have a similar interface.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'tcp'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/teddyknox/Workspace/Javascript/Node.js/nodejs-chat/server/server.js:5:11)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)

**Comment by bdotdub** [comment]
Should be resolved now. Let me know if not and I'll reopen!
